---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: file-contents-sorter
        files: requirements.txt|requirements-dev.txt
  # ------------------------- ops ------------------------
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x
          - -e
          - SC2086
      - id: shfmt
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - "2"
          - --sequence
          - "4"
          - --offset
          - "2"
          - --width
          - "150"
          - --preserve-quotes
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
#      - id: terraform_docs
#        args:
#          - --args=--config=.terraform-docs.yml
#       - id: terraform_tflint
      - id: terraform_tfsec
  # ------------------------- python ------------------------
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E402,E501"]
        exclude: ^migrations/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.6.0
    hooks:
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
#      - id: poetry-export
#        args: ["--with", "dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-black
